backend:
  name: test-repo
media_folder: static/assets
ppublic_folder: /images
# publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: 'content/blog'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    media_folder: ''
    public_folder: ''
    editor:
      preview: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description,  widget: text}
      - { name: body, label: Body, widget: markdown }
