backend:
  name: test-repo
  branch: main
media_folder: static/assets
ppublic_folder: /images
# publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: 'content/blog'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    media_folder: ''
    public_folder: ''
    editor:
      preview: true
    fields:
      # - { name: path, label: Path }
      - { name: type, label: Type, widget: hidden, default: blog}
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: featured, label: Featured, widget: boolean, default: false  }
      - { name: description, label: Description,  widget: text}
      - { name: tags, label: Tags, widget: list }
      - { name: headerImage, label: HeaderImage, widget: image, choose_url: true}
      - {
          name: related,
          label: Related-Blogs,
          widget: list,
          fields:
          [
            { label: Title, name: title, widget: string },
          ],
        }
      - { name: body, label: Body, widget: markdown }
  - name: wiki
    label: Wiki
    folder: 'content/wiki'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      # - { name: path, label: Path }
      - { name: type, label: Type, widget: hidden, default: wiki}
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description,  widget: text}
      - { name: thumbnail, label: Thumbnail,  widget: image}
      - { name: featured, label: Featured, widget: boolean, default: false  }
      - { name: tags, label: Tags, widget: list } # TODO: pull from wiki tags, make list
      - {
          label: Summary,
          name: summary,
          widget: list,
          fields:
            [
              { label: Field, name: field, widget: string },
              { label: Value, name: value, widget: string },
            ],
        }
      - { name: body, label: Body, widget: markdown }
